### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tschenkde** [larskotthoff/gnuplottex#10]
Not a real issue, just a little demand to update the documentation:
Could you please correct/update the Documentation (August 21, 2016)

1.) Put '--shell-escape' instead of '-shell-escape'
2.) explain how to set '\gnuplotexe'

I found many questions about the latter and it troubled me also:
I have several gnuplot versions, and "my" gnuplot points to a bash-script for choosing a version (if a parameter is given, otherwise it starts the standard version).
Latex runs gnuplot, but the shell-escape does not work any more after the bash-script.
Therefore, I had to put in the Latex-files : 

\def\gnuplotexe{/usr/local/bin/gnuplot}.

It would be nice to put (this as) an example of how to set  \gnuplotexe to the path instead of  saying : 'In addition, you can set \gnuplotexe to the path to the gnuplot executable. Normally, you don’t need to do this; use this option only if LATEX doesn’t find gnuplot.'

Thanks a lot in advance

**Comment by eg9** [comment]
@tschenkde The command line options to TeX binaries are given with a single hyphen, but also accept a double hyphen. If the documentation suggests `-shell-escape`, it is right.

**Comment by tschenkde** [comment]
Thanks for this info, looks like I did not test it after putting '\def\gnuplotexe{/usr/local/bin/gnuplot}' in the Latex-file.
