### ISSUE TITLE
not working for data from a file

### ISSUE THREAD

**Issue by dflvunoooooo** [larskotthoff/gnuplottex#22]
Latex reports `system returned with code 256` and is raising a waring if I try to plot data from a file. Of cause  there is no figure in the created in the latex pdf. The code seems to be converted properly in the .gnuplot file. There is no cleated pdf of the plot and the .tex plot file is empty. The code is working perfectly if run directly with gnuplot. 

 The waring is not helpful, it says `Gnuplot execution produced errors:plot 'Versuch_4_5_Gruppe_N_am_01_12_2023.dat' every 1::13::524 using 3:($6/$5) `. The latex code is:

```
\documentclass{scrreport}

\usepackage[siunitx, subfolder]{gnuplottex}

\begin{document}
	
\begin{figure}
	\centering
	\begin{gnuplot}[terminal=cairolatex, terminaloptions=color]
		
		plot 'Versuch_4_5_Gruppe_N_am_01_12_2023.dat' every 1::13::524 using 3:($6/$5)
	\end{gnuplot}
	\caption{This is a simple example using the cairolatex-terminal.}
	\label{pic:cairolatex}
\end{figure}

\end{document}
```

**Comment by larskotthoff** [comment]
Can you provide the contents of the file please?

**Comment by dflvunoooooo** [comment]
Of cause. It is a .dat file, but I am only allowed to upload .txt files, so I changed the ending.

[Versuch_4_5_Gruppe_N_am_01_12_2023.txt](https://github.com/larskotthoff/gnuplottex/files/13540681/Versuch_4_5_Gruppe_N_am_01_12_2023.txt)

**Comment by larskotthoff** [comment]
Thanks. After the error message you give, I get

    all points y value undefined!

I get exactly the same error when I run it in gnuplot directly, so it doesn't seem to be related to gnuplottex.

**Comment by dflvunoooooo** [comment]
You are right. The problem was a missing `set decimalsign locale "de_DE.UTF-8"` at the beginning to toll gnuplot to use a , as decimal seperator. Thank you for your assistance.
