### ISSUE TITLE
tikz not working in XeLatex

### ISSUE THREAD

**Issue by dflvunoooooo** [larskotthoff/gnuplottex#23]
The tikz terminal does not work when using XeLatex. Not sure if it is related to XeLatex, I do not have LuaLatex. If tikz terminal is set with XeLatex, I get the error `Package pgfkeys Error: I do not know the key '/tikz/gnuplot' and I am going to ignore it. Perhaps you misspelled it. \begin{tikzpicture}[gnuplot]`.  

Is tikz with XeLatex supported?

**Comment by larskotthoff** [comment]
`\usepackage{gnuplot-lua-tikz}`
