### ISSUE TITLE
Error if gnuplottex loaded but not used

### ISSUE THREAD

**Issue by fostermaier** [larskotthoff/gnuplottex#5]
`catchfile` results in an error when trying to locate the `*.gnuploterrors` file for documents in which `gnuplottex` ist loaded, but not used. Minimal working example:

> \documentclass{minimal}
> \usepackage{gnuplottex}
> \begin{document}
> \end{document}

XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016/Debian)
Package: gnuplottex 2015/12/13 v0.9.1 gnuplot graphs in LaTeX

**Comment by eg9** [comment]
The package is now `gnuplottex 2016/08/21 v0.9.2`

Commit https://github.com/larskotthoff/gnuplottex/commit/9ee95dd2d53df7b093a03578815f0ddc8f5e3fa6 should have solved the issue.

**Comment by fostermaier** [comment]
Of course! sorry, my bad.
